server:
  port: 8002
  
zuul:
    routes:
     Admin-service :
      url: http://localhost:8081
     Customer-Service:
      url: http://localhost:8082
     Order-Service:
      url: http://localhost:8083
     Payment-Service:
      url: http://localhost:8084
     Washer-Service :
     url: http://localhost:8085
      
     
       

     